version: "3.9"

services:
  resource-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: resource-db
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_PORT}:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    networks:
      - microservices-net

  song-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: song-db
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_PORT}:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    networks:
      - microservices-net

  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    container_name: resource-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://resource-db:5432/${RESOURCE_DB}"
      SPRING_DATASOURCE_USERNAME: "${RESOURCE_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${RESOURCE_DB_PASSWORD}"
    depends_on:
      - resource-db
    networks:
      - microservices-net

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    container_name: song-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://song-db:5432/${SONG_DB}"
      SPRING_DATASOURCE_USERNAME: "${SONG_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${SONG_DB_PASSWORD}"
    depends_on:
      - song-db
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
